CREATE TABLE IF NOT EXISTS USER (
    U_CODE INT NOT NULL AUTO_INCREMENT,
    U_ID VARCHAR(50) NOT NULL,
    U_PW VARCHAR(255) NOT NULL,
    U_NICK VARCHAR(50) NOT NULL,
    U_NAME VARCHAR(50) NOT NULL,
    U_BIRTH VARCHAR(20) NOT NULL,
    U_SEX INT NOT NULL,
    U_TEL VARCHAR(30) NOT NULL,
    U_MAIL VARCHAR(120) NOT NULL,
    U_ASSI INT NOT NULL DEFAULT 0,
    U_GOAL INT NOT NULL DEFAULT 0,
    U_CUT INT NOT NULL DEFAULT 0,
    USER_AUTH VARCHAR(30) NOT NULL DEFAULT 'ROLE_USER',
    PRIMARY KEY (U_CODE),
    UNIQUE KEY UK_USER_ID (U_ID)
);

CREATE TABLE IF NOT EXISTS TEAM (
    T_CODE INT NOT NULL AUTO_INCREMENT,
    T_IMG VARCHAR(255),
    T_NAME VARCHAR(80) NOT NULL,
    T_STADIUM VARCHAR(120),
    T_VIC INT NOT NULL DEFAULT 0,
    T_DRAW INT NOT NULL DEFAULT 0,
    T_LOSE INT NOT NULL DEFAULT 0,
    T_INTRO VARCHAR(500),
    PRIMARY KEY (T_CODE)
);

CREATE TABLE IF NOT EXISTS TEAM_MANAGEMENT (
    TM_CODE INT NOT NULL AUTO_INCREMENT,
    U_CODE INT NOT NULL,
    T_CODE INT NOT NULL,
    TM_ROLE VARCHAR(30) NOT NULL DEFAULT 'MEMBER',
    TM_STATUS VARCHAR(30) NOT NULL DEFAULT 'APPROVED',
    REG_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (TM_CODE),
    UNIQUE KEY UK_TEAM_USER (U_CODE, T_CODE),
    CONSTRAINT FK_TEAM_MANAGEMENT_USER FOREIGN KEY (U_CODE) REFERENCES USER (U_CODE),
    CONSTRAINT FK_TEAM_MANAGEMENT_TEAM FOREIGN KEY (T_CODE) REFERENCES TEAM (T_CODE)
);

CREATE TABLE IF NOT EXISTS FINFO (
    F_CODE INT NOT NULL AUTO_INCREMENT,
    F_AREA VARCHAR(80) NOT NULL,
    F_NAME VARCHAR(120) NOT NULL,
    F_ADD VARCHAR(255) NOT NULL,
    F_SOU VARCHAR(120),
    F_TEL VARCHAR(40),
    F_IMG VARCHAR(255),
    F_COST VARCHAR(120),
    F_HOURS VARCHAR(120),
    F_PARKING VARCHAR(120),
    F_SHOWER VARCHAR(120),
    F_NOTICE VARCHAR(500),
    PRIMARY KEY (F_CODE)
);

ALTER TABLE FINFO ADD COLUMN F_COST VARCHAR(120);
ALTER TABLE FINFO ADD COLUMN F_HOURS VARCHAR(120);
ALTER TABLE FINFO ADD COLUMN F_PARKING VARCHAR(120);
ALTER TABLE FINFO ADD COLUMN F_SHOWER VARCHAR(120);
ALTER TABLE FINFO ADD COLUMN F_NOTICE VARCHAR(500);

CREATE TABLE IF NOT EXISTS BOARD (
    IDX INT NOT NULL AUTO_INCREMENT,
    U_CODE INT NOT NULL,
    B_NICK VARCHAR(50) NOT NULL,
    B_TITLE VARCHAR(200) NOT NULL,
    B_CONTENTS TEXT NOT NULL,
    B_CNT INT NOT NULL DEFAULT 0,
    DEL_CHK CHAR(1) NOT NULL DEFAULT 'N',
    REG_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (IDX),
    CONSTRAINT FK_BOARD_USER FOREIGN KEY (U_CODE) REFERENCES USER (U_CODE)
);

CREATE TABLE IF NOT EXISTS GAMELIST (
    G_CODE INT NOT NULL AUTO_INCREMENT,
    G_DUNG INT NOT NULL,
    G_SEARCH INT,
    G_DATE DATE NOT NULL,
    G_TIME TIME NOT NULL,
    G_PEO VARCHAR(30) NOT NULL,
    G_MAGAM INT NOT NULL DEFAULT 1,
    F_CODE INT NOT NULL,
    G_INTRO VARCHAR(500),
    REG_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (G_CODE),
    CONSTRAINT FK_GAMELIST_HOME_TEAM FOREIGN KEY (G_DUNG) REFERENCES TEAM (T_CODE),
    CONSTRAINT FK_GAMELIST_AWAY_TEAM FOREIGN KEY (G_SEARCH) REFERENCES TEAM (T_CODE),
    CONSTRAINT FK_GAMELIST_FIELD FOREIGN KEY (F_CODE) REFERENCES FINFO (F_CODE)
);

CREATE TABLE IF NOT EXISTS persistent_logins (
    username VARCHAR(64) NOT NULL,
    series VARCHAR(64) PRIMARY KEY,
    token VARCHAR(64) NOT NULL,
    last_used TIMESTAMP NOT NULL
);
